# Generated by Django 3.0.8 on 2020-07-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200726_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'org')},
        ),
    ]
