# Generated by Django 3.0.8 on 2020-07-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200726_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'address', 'city')},
        ),
    ]
