# Generated by Django 3.0.8 on 2020-07-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ref_user_id',
            new_name='ref_user',
        ),
    ]
