# Generated by Django 3.0.8 on 2020-07-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('core', '0002_auto_20200724_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organiation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('nodal_officer', 'nodal_officer'), ('head_of_the_department', 'head_of_the_department'), ('employee_with_edit_permission', 'employee_with_edit_permission'), ('employee_with_view_permission', 'employee_with_view_permission')], default=None, max_length=35, null=True),
        ),
    ]
