# Generated by Django 3.0.8 on 2020-08-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('nodal_officer', 'nodal_officer'), ('head_of_the_department', 'head_of_the_department'), ('super_admin', 'super_admin')], default=None, max_length=35, null=True),
        ),
    ]
