# Generated by Django 3.0.8 on 2020-07-25 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('court', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lawyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('detail_doc', models.FileField(null=True, upload_to='documents')),
                ('status', models.CharField(choices=[('ADMISSION', 'ADMISSION'), ('ALLOCATED', 'ALLOCATED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RESPONDED', 'RESPONDED'), ('INITIATED', 'INITIATED'), ('PROCESS', 'PROCESS'), ('JUDGEMENT', 'JUDGEMENT')], max_length=15, null=True)),
                ('opponent_name', models.CharField(max_length=50, null=True)),
                ('opponent_contact_no', models.CharField(max_length=10, null=True)),
                ('opponent_email', models.CharField(max_length=50, null=True)),
                ('opponent_address', models.TextField()),
                ('next_hearing_at', models.DateField(null=True)),
                ('judgement', models.TextField()),
                ('judgement_at', models.DateField(null=True)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Victory', 'Victory'), ('Defeat', 'Defeat')], max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.Court')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.Practice_Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
