# Generated by Django 3.0.8 on 2020-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_user_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='judgement',
            field=models.TextField(null=True),
        ),
    ]
