# Generated by Django 3.0.8 on 2020-07-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_auto_20200728_0948'),
        ('case', '0006_auto_20200728_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.Practice_Area'),
        ),
    ]
