# Generated by Django 3.0.8 on 2020-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20200729_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_lawyers',
            name='status',
            field=models.CharField(choices=[('ADMISSION', 'ADMISSION'), ('ALLOCATED', 'ALLOCATED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RESPONDED', 'RESPONDED'), ('INITIATED', 'INITIATED'), ('PROCESS', 'PROCESS'), ('JUDGEMENT', 'JUDGEMENT')], max_length=15, null=True),
        ),
    ]
