# Generated by Django 3.0.8 on 2020-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20200729_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_invoices',
            name='gst',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='case_invoices',
            name='taxable_total',
            field=models.FloatField(null=True),
        ),
    ]
