# Generated by Django 3.0.8 on 2020-07-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20200730_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_invoices',
            name='taxable_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
