# Generated by Django 3.0.8 on 2020-07-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20200730_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_invoices',
            name='invoice_doc',
            field=models.FileField(null=True, upload_to='documents/invoices'),
        ),
        migrations.AlterField(
            model_name='case_invoices',
            name='gst',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
