# Generated by Django 3.0.8 on 2020-07-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_auto_20200730_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_invoices',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.lawyers'),
        ),
    ]
