# Generated by Django 3.0.8 on 2020-07-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_auto_20200730_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_invoices',
            name='lawyer',
        ),
    ]
