# Generated by Django 3.0.8 on 2020-08-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_remove_case_invoices_lawyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='description',
            new_name='action_at_final_order',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='result',
            new_name='decision_sought',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='judgement',
            new_name='final_order',
        ),
        migrations.AddField(
            model_name='cases',
            name='interim_order',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='rejoinder',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='reply',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
