# Generated by Django 3.0.8 on 2020-08-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_auto_20200802_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='action_at_final_order',
            new_name='case_synposis',
        ),
    ]
