# Generated by Django 3.0.8 on 2020-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0023_auto_20200803_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
