# Generated by Django 3.0.8 on 2020-08-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_cases_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='case_reminder',
            field=models.IntegerField(default=7, null=True),
        ),
    ]
