# Generated by Django 3.0.8 on 2020-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_auto_20200803_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
