# Generated by Django 3.0.8 on 2020-08-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_auto_20200803_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_table',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.lawyers'),
        ),
    ]
