# Generated by Django 3.0.8 on 2020-08-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_auto_20200803_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='final_order',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='interim_order',
        ),
        migrations.AlterField(
            model_name='cases',
            name='rejoinder',
            field=models.FileField(blank=True, null=True, upload_to='documents/rejoinder'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='reply',
            field=models.FileField(blank=True, null=True, upload_to='documents/reply'),
        ),
    ]
