# Generated by Django 3.0.8 on 2020-08-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0029_auto_20200803_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_hearings',
            name='status',
            field=models.CharField(choices=[('Interim', 'Interim'), ('Final', 'Final')], max_length=15, null=True),
        ),
    ]
