# Generated by Django 3.0.8 on 2020-08-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0030_auto_20200803_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_hearings',
            old_name='status',
            new_name='order_type',
        ),
    ]
